dist: trusty

language: java

jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.m2"

addons:
  sonarqube:
    token:
      secure: VfCcVnsI/H6kjVLbIrJ2ZYtdlphr3arBovAG7tSAKdASffgqpcLbPD5Kjcb0sRyYRHMWjonrNSaCQVhMC4PDwfHqQd1joy0AM+d6vlPnxHsIDA1x9HNHblgkiKyxRO8kzo6I8fQtUZ5bLbwR18SfjHYWPYRPXfXmJQFYyfQAG/x4YPzdcJhIMH1Lv49wJoxpjnj7UEopBON84y11gLuP5i3WUTJ4UlG8G/sc+1OZr9P+HPgG3XGNDV7r5Q6WtTuMlrd90afUQvltkDAFb8NejPXErXEHtVf9M/PSRBprALuflq7idnlifd+sRri20hn2I9iTzkalkqAzgphasXxMEzo3MAxdNJ/h+utYNI+PKLV9AGJkRx1WW9hDdW8hEEF+N73bBKlm+iBjROFjTOUuKQ5ISeGwbUcMqctyrk6a867tUEq4Wl1+0JyEKr9TuxDEsqH3ZsE/RuqBTksXGhaNyNw3a4/Qip7SGPfuCSL8RteEdMG1RlrY5EqAvNS9FWvNjjk5aS8WEVW0uxAHDgk3XNV4YqTQxjt347VF+6xdBXSsnIw1fUTl3DpWeUCwrF14fY4BGtUcw3/lPoejo/y6VZ8xUS5mX0EWM38xZaFGmA2VgZd/3HaD0fRzvkl4zgn0pPmewqoAe7jBesTN+AcCsk04AruiKn6uGKxqrDu8cGo=
    github_token:
      secure: iuJIupPpcvrCDGFveKuIeNF/uXHWGSgPw8rzOvJvL1R6VqI37APwunSJyjnDjUQt84WYVCGPQc2W8CRQM7IYUFBijK0BI5Edact+Ba1ER6SIms4C0H/4vWzgMzaW8ACJc20GtD1drQjPVIHc8JUPWiYQyvR3xMqdaej/hQsigkl409C/R0UFRoprV7DipkHqZb8k36PQ4tyd1FMMf1PgSkdiOj/G3rM9xKEhplth46JMnSN480Nb10C8Vc1LKLzKj8oA5AdSRNAe7QDaVPgYgSkkLei8YkMca8GdhCVDLfF//gHbvYfher3PcjpbIm4TiWPHIPzkjitWCMdlSRaUpPjs171DvDt8h778QSYTkA3Mg4zzNPoWIzUNusIP2XQsSguLit5aoP0Ac045rHFbr7CsjMcLgsaGM5YhgAoux86qPZRwF8gpKbXV9Ng3ITcnHw/6T4BAvCr96xwEj8wi49SfSdjSrTwl5TIbIxsXiEA7EFAHwYHDSmhcIjLLt5INDJ9549j6SpIGymiSWqKDMF7XXULSof9DBpfBuzCxrsnrUX+hDSCuqs2JUc/7Qg3vADV6LZ1LS33eqW1oRPHet4TXn+eaXdpkaFrkeNPbDjxDE5HMiY416jOy33rZY/h1cE2uu3MXerNm4X08UGV+oTfvHxP4ma/vXUAHUcvkISg=

script:
  - mvn clean test jacoco:report coveralls:report
  - sonar-scanner
